const {createClient}=window.supabase;
const db=createClient(window.APP_CONFIG.SUPABASE_URL,window.APP_CONFIG.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const TOKEN_KEY="client_opportunity_device_token";
function token(){let t=localStorage.getItem(TOKEN_KEY);if(!t){t=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem(TOKEN_KEY,t)}return t}
async function register(){const {error}=await db.rpc("register_device",{p_device_token:token()});if(error)throw error}
function calc(net,age,rate){return net*Math.pow(1+rate/100,Math.max(0,80-age))}
function preview(){const a=+$("current_age").value,n=+$("current_net_worth").value,r=+$("growth_rate").value;if(!a||n<0||r<0){$("projected-preview").textContent="$0";$("projection-note").textContent="Enter age and net worth to preview.";return}$("projected-preview").textContent=money(calc(n,a,r));$("projection-note").textContent=`${Math.max(0,80-a)} years projected at ${r}% annual growth.`}
["current_age","current_net_worth","growth_rate"].forEach(id=>$(id).addEventListener("input",preview));
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");if(b.dataset.tab==="past-clients")load()});
$("clear-btn").onclick=()=>{$("client-form").reset();$("growth_rate").value=4;$("result").className="result hidden";$("form-message").textContent="";preview()};
$("client-form").onsubmit=async e=>{e.preventDefault();$("save-btn").disabled=true;$("form-message").textContent="Saving client...";try{await register();const age=+$("current_age").value,net=+$("current_net_worth").value,rate=+$("growth_rate").value,death=+$("life_insurance_death_benefit").value,projected=calc(net,age,rate),high=projected>14000000;const {error}=await db.rpc("save_client",{p_device_token:token(),p_full_name:$("full_name").value.trim(),p_phone_number:$("phone_number").value.trim(),p_current_age:age,p_life_insurance_death_benefit:death,p_current_net_worth:net,p_growth_rate:rate,p_projected_net_worth:projected,p_high_net_worth:high});if(error)throw error;$("form-message").textContent="Client saved successfully."; $("result").className=`result ${high?"alert-result":"good-result"}`;$("result").innerHTML=high?`<strong>High net worth client detected!</strong><span>Projected net worth at age 80: ${money(projected)}</span>`:`<strong>Good news!</strong><span>Talk to the host for a special opportunity available to only a select few... including you!</span><small>Projected net worth at age 80: ${money(projected)}</small>`}catch(err){$("form-message").textContent="Could not save: "+err.message}finally{$("save-btn").disabled=false}};
async function load(){const list=$("clients-list");list.innerHTML='<div class="empty-state">Loading saved clients...</div>';try{await register();const {data,error}=await db.rpc("get_clients",{p_device_token:token()});if(error)throw error;window.clients=data||[];render()}catch(e){list.innerHTML=`<div class="empty-state error-text">Could not load clients: ${e.message}</div>`}}
function render(){const q=$("search").value.toLowerCase().trim(),f=$("filter").value,arr=window.clients.filter(c=>(!q||c.full_name.toLowerCase().includes(q)||c.phone_number.toLowerCase().includes(q))&&(f==="all"||(f==="high"?c.high_net_worth:!c.high_net_worth)));if(!arr.length){$("clients-list").innerHTML='<div class="empty-state">No matching clients.</div>';return}$("clients-list").innerHTML=arr.map(c=>`<button class="client-row" data-id="${c.id}"><div class="client-main"><strong>${esc(c.full_name)}</strong><span>${esc(c.phone_number)} · Age ${c.current_age}</span></div><div class="client-value ${c.high_net_worth?"high-value":""}">${money(c.projected_net_worth)}<small>${c.high_net_worth?"High net worth":"Projected at 80"}</small></div></button>`).join("");document.querySelectorAll(".client-row").forEach(r=>r.onclick=()=>show(window.clients.find(c=>c.id===r.dataset.id)))}
function show(c){$("detail-name").textContent=c.full_name;$("detail-content").innerHTML=`<div><span>Phone</span><strong>${esc(c.phone_number)}</strong></div><div><span>Current age</span><strong>${c.current_age}</strong></div><div><span>Life insurance death benefit</span><strong>${money(c.life_insurance_death_benefit)}</strong></div><div><span>Current net worth</span><strong>${money(c.current_net_worth)}</strong></div><div><span>Annual growth rate</span><strong>${c.growth_rate}%</strong></div><div><span>Projected net worth at 80</span><strong>${money(c.projected_net_worth)}</strong></div><div><span>Saved</span><strong>${new Date(c.created_at).toLocaleString()}</strong></div><div><span>Status</span><strong class="${c.high_net_worth?"high-value":""}">${c.high_net_worth?"High net worth client":"Standard"}</strong></div>`;$("details-modal").classList.remove("hidden")}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("modal-close").onclick=()=>$("details-modal").classList.add("hidden");$("details-modal").querySelector(".modal-backdrop").onclick=()=>$("details-modal").classList.add("hidden");$("refresh-btn").onclick=load;$("search").oninput=render;$("filter").onchange=render;preview();